//Live URL
var BaseUrl = "https://www.reibens.com/";

//Local URL
//var BaseUrl = "http://localhost:63808/";

angular.module('app.config', []).constant('config', {
    txtGrantType: "password",
    txtLoginAlert: "All login form elements must be populated.",
    txtLoginFailure400: "Unfortunately, there is an issue with your account. Please contact Tech Support.",
    txtLoginFailure: "This application is currently experiencing technical difficulties. Please contact Tech Support.",
    epLoginToken: BaseUrl + "token",
    epGetUserInfo: BaseUrl + "getuserinfo",
    epGetUserProfile: BaseUrl + "getprofileinfo",
    epGetUserProfileInfo: BaseUrl + "getuserprofileinfo?userId=",
    epModifyUserSettingsDemographics: BaseUrl + "modifyusersettingsdemographics?userId=",
    epModifyUserPassword: BaseUrl + "modifyuserpassword",
    epGetUserPassword: BaseUrl + "getuserpassword?userId=",
    epGetStates: BaseUrl + "getstates",
    epGetSubscriptions: BaseUrl + "getSubscriptions?userId=",
    epGetFaqs: BaseUrl + "getfaqs",
    epGetInvestorTypes: BaseUrl + "getinvestortypes",
    epUpdateUserInvestorTypes: BaseUrl + "updateuserInvestortypes",
    epChangeSubscription: BaseUrl + "changesubscription",
    epCancelSubscription: BaseUrl + "cancelsubscription?userId=",
    epGetHelpTopics: BaseUrl + "gethelptopics",
    epSaveConcern: BaseUrl + "saveconcern",
    epGetAllActiveUsers: BaseUrl + "getallactiveusers?userId=",
    epSearchForUser: BaseUrl + "searchforuser?",
    epViewAUser: BaseUrl + "viewauser?",
    epSaveUserRank: BaseUrl + "saveuserrank?",
    epGetAllUserRankRequests: BaseUrl + "getalluserrankrequests",
    epApproveDenyUserRank: BaseUrl + "approvedenyuserrank",
    epGetActiveHelpCenterRequests: BaseUrl + "getactivehelpcenterrequests",
    epUpdateHelpCenterRequest: BaseUrl + "updatehelpcenterrequest",
    epGetAllUserActivities: BaseUrl + "getalluseractivities",
    epGetResolvedHelpCenteRrequests: BaseUrl + "getresolvedhelpcenterrequests",
    epGetAllUsers: BaseUrl + "getallusers",
    epEnabledisableuser: BaseUrl + "enabledisableuser",
    epGetAllRankedUnrankedUserRequests: BaseUrl + "getallrankedunrankeduserrequests",
    epGetAllRoles: BaseUrl + "getallroles",
    epCreateRole: BaseUrl + "createrole",
    epUpdateRole: BaseUrl + "updaterole",
    epDeleteRole: BaseUrl + "deleterole",
    epGetUserRoles: BaseUrl + "getuserroles",
    epCreateUpdateUserRoles: BaseUrl + "createupdateuserroles",
    epSignUp: BaseUrl + "signup",
    epGetAllFaq: BaseUrl + "getallfaqs",
    epCreateFaq: BaseUrl + "createfaq",
    epUpdateFaq: BaseUrl + "updatefaq",
    epDeleteFaq: BaseUrl + "deletefaq",
    epGetTotalNoOfBennies: BaseUrl + "gettotalnoofbennies?userId=",
    epGetTotalNoOfBenniesSignedUpPerMonth: BaseUrl + "gettotalnoofbenniessigneduppermonth?userId=",
    epGetTotalNoOfSubscriptions: BaseUrl + "gettotalnoofsubscriptions?userId=",
    epGetTotalNoOfHelpRequestPerMonth: BaseUrl + "gettotalnoofhelprequestpermonth?",
    epGetTotalRevenuePerMonth: BaseUrl + "gettotalrevenuepermonth?userId=",
    epGetTotalNoOfBenniesRankings: BaseUrl + "gettotalnoofbenniesrankings?userId=",
    epGetTotalNoOfBenniesSignedUpPerState: BaseUrl + "gettotalnoofbenniessignedupperstate?userId=",
    epSendFcmNotification: BaseUrl + "sendfcmnotification?",
    epGetTotalRevenuePerYear: BaseUrl + "gettotalrevenueperyear?userId=",
    epGetAllCalendarItems: BaseUrl + "getallcalendaritems",
    epSendFcmNotificationToAllUsers: BaseUrl + "sendfcmnotificationtoallusers?",
    epSendFcmNotificationToMultiUsers :BaseUrl + "sendfcmnotificationtomultiusers?",
    epGetTotalNoOfBenniesSignedUpPerMonthByYear: BaseUrl + "gettotalnoofbenniessigneduppermonthbyyear?",
    epGetTotalNoOfSubscriptionsByYear: BaseUrl + "gettotalnoofsubscriptionsbyyear?",
    epGetTotalNoofBenniesSignedUpPerStateByYear: BaseUrl + "gettotalnoofbenniessignedupperstatebyyear?",
    epGetTotalRevenuePerMonthByYear: BaseUrl + "gettotalrevenuepermonthbyyear?",
    epGetTotalNoOfHelpRequestPerMonthByYear: BaseUrl + "gettotalnoofhelprequestpermonthbyyear?",
    epGetTotalNoOfBenniesSignedUpPerMonthByYearMonth: BaseUrl + "gettotalnoofbenniessigneduppermonthbyyearmonth?",
    epGetTotalNoOfSubscriptionsByYearMonth: BaseUrl + "gettotalnoofsubscriptionsbyyearmonth?",
    epGetTotalNoOfBenniesSignedupPerStateByYearMonth: BaseUrl + "gettotalnoofbenniessignedupperstatebyyearmonth?",
    epGetTotalNoOfHelpRequestPerMonthByYearMonth: BaseUrl + "gettotalnoofhelprequestpermonthbyyearmonth?",
    epGetTotalRevenuePerMonthByYearMonth: BaseUrl + "gettotalrevenuepermonthbyyearmonth?",
    epGetAllFcmPushNotifications: BaseUrl + "getallfcmpushnotifications?userId=",
    epGetAllMarketPlaces: BaseUrl + "getallmarketplaces",
    epGeneratePromoCode: BaseUrl + "generatepromocode?userId=",
    epCreatePromoCode: BaseUrl + "createpromocode",
    epUpdatePromoCode: BaseUrl + "updatepromocode",
    epDeletePromoCode: BaseUrl + "deletepromocode?promoCodeId=",
    epGetAllPromoCodes: BaseUrl + "getallpromocodes?",
    epGetUserListByRoleId: BaseUrl + "getuserlistbyroleid?roleId=",
    epGetUserListByPromoCode: BaseUrl + "getuserlistbypromocode?",
    epGetAllActiveUsersByRoleId: BaseUrl + "getallactiveusersbyroleid?",
    epActivateUserAccount: BaseUrl + "activateuseraccount",
    epGetUserActivationInfo: BaseUrl + "getuseractivationinfo?userId=",
    epCreateUserActivationSubscription: BaseUrl + "createuseractivationsubscription?userId="

    //epgetallcalendaritemsday: BaseUrl + "getallcalendaritemsday?"
}); 
